version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.9.5
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      sudo pip install --upgrade pip
      pip install --user tox

fetch_data: &fetch_data
  run:
    name: Set script permissions and fetch data
    command: |
      source venv/bin/activate
      chmod +x ./scripts/fetch_kaggle_dataset.sh
      ./scripts/fetch_kaggle_dataset.sh

jobs:
  test_app:
    <<: *defaults
    working_directory: ~/project/house-price-api
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Runnning app tests
          command: |
            tox

  section_07_deploy_app_to_heroku:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Deploy to Heroku
          command: |
            git subtree push --prefix house-price-api https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

  test_regression_model:
    <<: *defaults
    working_directory: ~/project/model-package
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Fetch the data
          command: |
            tox -e fetch_data
      - run:
          name: Test the model
          command: |
            tox

  test_and_upload_regression_model:
    <<: *defaults
    working_directory: ~/project/model-package
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Fetch the data
          command: |
            tox -e fetch_data
      - run:
          name: Test the model
          command: |
            tox
      - run:
          name: Publish model to Gemfury
          command: |
            tox -e publish_model

  build_and_push_to_heroku_docker:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker login --username=$HEROKU_EMAIL --password=$HEROKU_API_KEY registry.heroku.com
      - run:
          name: Setup Heroku CLI
          command: |
            wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run:
          name: Build and Push Image
          command: |
            make build-ml-api-heroku push-ml-api-heroku
      - run:
          name: Release to Heroku
          command: |
            heroku container:release web --app $HEROKU_APP_NAME

  publish_docker_image_to_aws:
    <<: *defaults
    working_directory: ~/project/house-price-api
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publishing docker image to aws ECR
          command: |
            sudo pip install awscli
            eval $(aws ecr get-login --no-include-email --region us-east-1)
            make build-ml-api-aws tag-ml-api push-ml-api-aws
            aws ecs update-service --cluster ml-api-cluster --service custom-service --task-definition  first-run-task-definition --force-new-deployment

tags_only: &tags_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^.*/

workflows:
  version: 2
  section_07:
    jobs:
      - test_app
      - test_regression_model
      - build_and_push_to_heroku_docker: # build_and_push_to_heroku_docker #  publish_docker_image_to_aws:
          requires:
            - test_app
          filters:
            branches:
              only:
                - main
      # upload after git tags are created
      - test_and_upload_regression_model:
          <<: *tags_only
#      - section_08_deploy_app_container_in_heroku:
#          filters:
#            branches:
#              only:
#                - main


#  test-all:
#    jobs:
#      - test_regression_model_py36
#      - test_regression_model_py37
#      - test_regression_model_py38
#      - test_ml_api_py36
#      - test_ml_api_py37
#      # - test_ml_api_py38 pending NN model update
#      - section_9_differential_tests
#      - train_and_upload_regression_model:
#          requires:
#            - test_regression_model_py36
#            - test_regression_model_py37
#            - test_regression_model_py38
#            - test_ml_api_py36
#            - test_ml_api_py37
#            - section_9_differential_tests
#          filters:
#            branches:
#              only:
#                - master
#       - section_10_deploy_to_heroku:
#           requires:
#             - train_and_upload_regression_model
#           filters:
#             branches:
#               only:
#                 - master
#      - section_11_build_and_push_to_heroku_docker:
#          requires:
#            - train_and_upload_regression_model
#          filters:
#            branches:
#              only:
#                - master
#       - section_12_publish_docker_image_to_aws:
#           requires:
#             - train_and_upload_regression_model
#           filters:
#             branches:
#               only:
#                 - master
#      - section_13_train_and_upload_neural_network_model:
#          requires:
#            - test_regression_model
#            - test_ml_api
#            - section_9_differential_tests
#             - train_and_upload_regression_model
#           filters:
#             branches:
#               only:
#                 - master
